### ISSUE TITLE
'yarn demo' errors after scaffolding project

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [diez/diez#6]
After scaffolding my Diez project by following the [getting started](https://diez.org/getting-started/#set-up) instructions, I'm stuck on an error when running `yarn demo`.
```bash
'C:\VinnuStundIntelliJ\VVFrontEndModules\packages\apps\vv-design\design-language\node_modules\diez\bin\diez' is not recognized as an internal or external command,
operable program or batch file.
Command failed: C:\VinnuStundIntelliJ\VVFrontEndModules\packages\apps\vv-design\design-language\node_modules\diez\bin\diez compile -t web
error Command failed with exit code 1.
```

Screenshots from git bash:
![image](https://user-images.githubusercontent.com/5609118/69065111-1b7e2980-0a17-11ea-8d6a-593a781aa094.png)

Strangely, I was able to call the compile command straight from node_modules, but only if I had quotes around the path (since it was backwards slash).
![image](https://user-images.githubusercontent.com/5609118/69066262-e377e600-0a18-11ea-95da-7ded9cb77ce0.png)

Also worked by directly using node
![image](https://user-images.githubusercontent.com/5609118/69066392-220da080-0a19-11ea-8af2-79dfe8972983.png)

![image](https://user-images.githubusercontent.com/5609118/69065758-22596c00-0a18-11ea-88b7-1c90af1a83e2.png)

I've tried different versions of node, with no luck.
I've also tried using cmd, but the same error occured.

| Software | Version  |
| ------------- | ------------- |
| nodejs  | 12.13.0, 10.16.3  |
| yarn  | 1.19.1  |
| diez  | ^10.0.0-beta.6  |

**OS:** Windows 10
**Terminal:** Hyper with git bash, cmd

**Comment by roperzh** [comment]
Hey @hrafnkellbaldurs! thank you very much for such a nice report 🤗. Seems like we need to figure out a better way to do [this](https://github.com/diez/diez/blob/1c1e2565217ef9001f95450e178249f6b92eb475/src/utils/start/src/index.action.ts#L48-L75)

I'm currently investigating/fixing the issue and I will get back to you as soon as it's fixed.

**Comment by hrafnkellbaldurs** [comment]
This is working for me now, thanks for the quick response 🚴🔥

**Comment by roperzh** [comment]
wohoo! thanks for reaching out! 🤗

**Comment by yuriybelike** [comment]
Experiencing the same issue even having the latest diez version...

Thing | Version
------|----------
OS | Windows 10
Diez | 10.2.1
Yarn | 1.22.0
Node | 10.16.3
Terminal | Powershell

**Comment by roperzh** [comment]
Hey @yuriybelike, I'm very sorry you had troubles, I was able to repro and we just released version `10.2.3` with a fix 🎉 .

If you run `yarn create diez` again, your project will be created with the latest version of diez. Please let me know if I can be of any help!

**Comment by JSMike** [comment]
@roperzh I'm still experiencing issues with the diez CLI in 10.6.0 on windows using git-bash. Running `yarn demo` results in windows style paths being used in a bash environment. I had to `npm config delete script-shell` in order for `yarn demo` to work on windows (or i guess i could override script-shell in a local .npmrc).
